# Generated by Django 3.2.13 on 2022-06-09 15:57

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('date_of_birht', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=catalog.models.image_rename, verbose_name='портрет')),
                ('about', models.TextField(blank=True, help_text='Об авторе', max_length=2000, null=True, verbose_name='об авторе')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'авторы',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите язык книги (русский, английский)', max_length=200, verbose_name='язык')),
            ],
            options={
                'verbose_name': 'язык',
                'verbose_name_plural': 'языки',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название издательства')),
            ],
            options={
                'verbose_name': 'издательство',
                'verbose_name_plural': 'издательства',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тег', max_length=30, verbose_name='название тега')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('summary', models.TextField(help_text='Введите короткое описание содержимого книги', max_length=2000, verbose_name='краткое содержание')),
                ('isbn', models.CharField(help_text='13 символов <a href="https://www.isbn-international.org/content/what-isbn">ISBN</a>', max_length=13, unique=True, verbose_name='ISBN')),
                ('year', models.SmallIntegerField(blank=True, null=True, verbose_name='год издания')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=catalog.models.image_rename, verbose_name='обложка')),
                ('num_pages', models.IntegerField(blank=True, null=True, verbose_name='количество страниц')),
                ('author', models.ManyToManyField(related_name='book', to='catalog.Author', verbose_name='автор')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language', verbose_name='язык')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.publisher', verbose_name='издательство')),
                ('tag', models.ManyToManyField(blank=True, help_text='Выберите теги для этой книги', related_name='book', to='catalog.Tag', verbose_name='тег')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
